In [131]:

import numpy as np
import pandas as pd


def get_daily_avg_dec_to_mar(provider_code="R0A"):
    daily_data = pd.read_excel("./data/Daily Average Data.xlsx")

    daily_data["Date"] = pd.to_datetime(daily_data["Date"], errors='coerce')

    daily_data["Date"] = pd.to_datetime(daily_data["Date"], format="%Y-%m")

    x = daily_data.groupby('Provider_Code')

    selected_Provider = x.get_group(provider_code)
    selected_Provider.head()

    sample_std = selected_Provider.std(ddof=0)
    sample_mean = selected_Provider.mean()

    selected_Provider = selected_Provider[selected_Provider["Date"]=="2023-03-31"]

    features = [
        "Daily_Average_Staff_Absence",
        "Arriving_by_ambulance",
        "Time_Lost_to_Ambulance_Handover_Delays_Hours",
        "Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside",
        "Daily_Avg_Bed_Occupancy>7 days",
        "Daily_Avg_Bed_Occupancy>14 days",
        "Daily_Avg_Bed_Occupancy>21 days"
    ]

    std_away = (selected_Provider[features] -
                sample_mean[features])/sample_std[features]
    std_away = std_away + (std_away > 0)
    std_away = (std_away*10)//10

    std_away[std_away >= 5] = 4
    std_away[std_away <= -5] = -4

    return std_away

get_daily_avg_dec_to_mar()

C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\3481867634.py:17: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_std = selected_Provider.std(ddof=0)
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\3481867634.py:18: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  sample_mean = selected_Provider.mean()
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\3481867634.py:18: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_mean = selected_Provider.mean()

,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
315,-2.0,2.0,-1.0,1.0,-1.0,1.0,2.0

In [135]:
def get_daily_avg_mar_all_hospital(date="2023-03-31"):

    daily_data = pd.read_excel("./data/Daily Average Data.xlsx")

    daily_data["Date"] = pd.to_datetime(daily_data["Date"], errors='coerce')

    daily_data["Date"] = pd.to_datetime(daily_data["Date"], format="%Y-%m")

    x = daily_data.groupby('Date')

    selected_Provider = x.get_group(date)
    selected_Provider.head()

    sample_std = selected_Provider.std(ddof=0)
    sample_mean = selected_Provider.mean()

    selected_Provider = selected_Provider.set_index("Provider_Code")

    features = [
        "Daily_Average_Staff_Absence",
        "Arriving_by_ambulance",
        "Time_Lost_to_Ambulance_Handover_Delays_Hours",
        "Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside",
        "Daily_Avg_Bed_Occupancy>7 days",
        "Daily_Avg_Bed_Occupancy>14 days",
        "Daily_Avg_Bed_Occupancy>21 days"
    ]

    std_away = (selected_Provider[features] -
                sample_mean[features])/sample_std[features]
    std_away = std_away + (std_away > 0)
    std_away = (std_away*10)//10

    std_away[std_away >= 5] = 4
    std_away[std_away <= -5] = -4

    return std_away


get_daily_avg_mar_all_hospital(date="2023-03-31")

C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\4270764940.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_std = selected_Provider.std(ddof=0)
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\4270764940.py:15: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  sample_mean = selected_Provider.mean()
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\4270764940.py:15: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_mean = selected_Provider.mean()

,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
Provider_Code,,,,,,,
R0A,4,3.0,-1.0,4,3.0,4.0,4.0
R0B,1.0,1.0,-1.0,1.0,1.0,1.0,1.0
R1H,1.0,2.0,1.0,1.0,2.0,2.0,2.0
R1K,-1.0,2.0,-1.0,-1.0,1.0,1.0,1.0
RA2,-1.0,-2.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...
RXP,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0
RXQ,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
RXR,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0
RXW,1.0,-1.0,2.0,-1.0,-1.0,-1.0,-1.0
RYR,3.0,4.0,-1.0,4.0,4.0,4.0,4.0

In [3]:
import numpy as np
import pandas as pd

In [95]:
daily_data = pd.read_excel("./data/Daily Average Data.xlsx")

In [96]:
daily_data["Date"] = pd.to_datetime(daily_data["Date"], errors='coerce')

In [105]:
daily_data.head()

,Provider_Code,Date,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
0,R0A,2022-12-31,1792,172,43.45,252,1023,657,452
1,R0B,2022-12-31,671,104,22.52,87,510,316,211
2,R1H,2022-12-31,602,162,40.16,297,703,436,289
3,R1K,2022-12-31,390,132,45.71,45,507,279,176
4,RA2,2022-12-31,180,39,1.94,21,304,195,141

In [99]:
daily_data["Date"] = pd.to_datetime(daily_data["Date"] , format="%Y-%m")

In [101]:
daily_data["Date"]

0     2022-12-31
1     2022-12-31
2     2022-12-31
3     2022-12-31
4     2022-12-31
         ...
415   2023-03-31
416   2023-03-31
417   2023-03-31
418   2023-03-31
419   2023-03-31
Name: Date, Length: 420, dtype: datetime64[ns]

In [119]:
x = daily_data.groupby('Provider_Code')

In [128]:
provider_codes = daily_data["Provider_Code"].unique()

In [129]:
[{'label': i, 'value': i} for i in provider_codes]

[{'label': 'R0A', 'value': 'R0A'},
 {'label': 'R0B', 'value': 'R0B'},
 {'label': 'R1H', 'value': 'R1H'},
 {'label': 'R1K', 'value': 'R1K'},
 {'label': 'RA2', 'value': 'RA2'},
 {'label': 'RA7', 'value': 'RA7'},
 {'label': 'RA9', 'value': 'RA9'},
 {'label': 'RAE', 'value': 'RAE'},
 {'label': 'RAJ', 'value': 'RAJ'},
 {'label': 'RAL', 'value': 'RAL'},
 {'label': 'RAP', 'value': 'RAP'},
 {'label': 'RAS', 'value': 'RAS'},
 {'label': 'RAX', 'value': 'RAX'},
 {'label': 'RBD', 'value': 'RBD'},
 {'label': 'RBK', 'value': 'RBK'},
 {'label': 'RBL', 'value': 'RBL'},
 {'label': 'RBN', 'value': 'RBN'},
 {'label': 'RBT', 'value': 'RBT'},
 {'label': 'RCB', 'value': 'RCB'},
 {'label': 'RCD', 'value': 'RCD'},
 {'label': 'RCF', 'value': 'RCF'},
 {'label': 'RCX', 'value': 'RCX'},
 {'label': 'RD1', 'value': 'RD1'},
 {'label': 'RN3', 'value': 'RN3'},
 {'label': 'RD8', 'value': 'RD8'},
 {'label': 'RNZ', 'value': 'RNZ'},
 {'label': 'RRK', 'value': 'RRK'},
 {'label': 'RDE', 'value': 'RDE'},
 {'label': 'RTH', 'value': 'RTH'},
 {'label': 'RHW', 'value': 'RHW'},
 {'label': 'RGN', 'value': 'RGN'},
 {'label': 'RJR', 'value': 'RJR'},
 {'label': 'RJN', 'value': 'RJN'},
 {'label': 'REM', 'value': 'REM'},
 {'label': 'REF', 'value': 'REF'},
 {'label': 'RLT', 'value': 'RLT'},
 {'label': 'RJC', 'value': 'RJC'},
 {'label': 'RKB', 'value': 'RKB'},
 {'label': 'RR7', 'value': 'RR7'},
 {'label': 'RNN', 'value': 'RNN'},
 {'label': 'RTF', 'value': 'RTF'},
 {'label': 'RTD', 'value': 'RTD'},
 {'label': 'RH8', 'value': 'RH8'},
 {'label': 'RF4', 'value': 'RF4'},
 {'label': 'RQX', 'value': 'RQX'},
 {'label': 'RTE', 'value': 'RTE'},
 {'label': 'RMC', 'value': 'RMC'},
 {'label': 'RFF', 'value': 'RFF'},
 {'label': 'RM3', 'value': 'RM3'},
 {'label': 'RMP', 'value': 'RMP'},
 {'label': 'RRF', 'value': 'RRF'},
 {'label': 'RN5', 'value': 'RN5'},
 {'label': 'RHM', 'value': 'RHM'},
 {'label': 'RFS', 'value': 'RFS'},
 {'label': 'RLQ', 'value': 'RLQ'},
 {'label': 'RQW', 'value': 'RQW'},
 {'label': 'RJL', 'value': 'RJL'},
 {'label': 'RTG', 'value': 'RTG'},
 {'label': 'RN7', 'value': 'RN7'},
 {'label': 'RGP', 'value': 'RGP'},
 {'label': 'RPA', 'value': 'RPA'},
 {'label': 'RH5', 'value': 'RH5'},
 {'label': 'RM1', 'value': 'RM1'},
 {'label': 'RRV', 'value': 'RRV'},
 {'label': 'RKE', 'value': 'RKE'},
 {'label': 'RHQ', 'value': 'RHQ'},
 {'label': 'RNS', 'value': 'RNS'},
 {'label': 'RJ1', 'value': 'RJ1'},
 {'label': 'RK5', 'value': 'RK5'},
 {'label': 'RJ2', 'value': 'RJ2'},
 {'label': 'RJZ', 'value': 'RJZ'},
 {'label': 'RJ6', 'value': 'RJ6'},
 {'label': 'RJ7', 'value': 'RJ7'},
 {'label': 'RP5', 'value': 'RP5'},
 {'label': 'RJE', 'value': 'RJE'},
 {'label': 'RNA', 'value': 'RNA'},
 {'label': 'RL4', 'value': 'RL4'},
 {'label': 'RR8', 'value': 'RR8'},
 {'label': 'RTK', 'value': 'RTK'},
 {'label': 'RTP', 'value': 'RTP'},
 {'label': 'RTR', 'value': 'RTR'},
 {'label': 'RTX', 'value': 'RTX'},
 {'label': 'RVJ', 'value': 'RVJ'},
 {'label': 'RVR', 'value': 'RVR'},
 {'label': 'RVV', 'value': 'RVV'},
 {'label': 'RVY', 'value': 'RVY'},
 {'label': 'RWA', 'value': 'RWA'},
 {'label': 'RWD', 'value': 'RWD'},
 {'label': 'RWE', 'value': 'RWE'},
 {'label': 'RWF', 'value': 'RWF'},
 {'label': 'RWG', 'value': 'RWG'},
 {'label': 'RWH', 'value': 'RWH'},
 {'label': 'RWJ', 'value': 'RWJ'},
 {'label': 'RWP', 'value': 'RWP'},
 {'label': 'RWW', 'value': 'RWW'},
 {'label': 'RWY', 'value': 'RWY'},
 {'label': 'RXC', 'value': 'RXC'},
 {'label': 'RXK', 'value': 'RXK'},
 {'label': 'RXL', 'value': 'RXL'},
 {'label': 'RXN', 'value': 'RXN'},
 {'label': 'RXP', 'value': 'RXP'},
 {'label': 'RXQ', 'value': 'RXQ'},
 {'label': 'RXR', 'value': 'RXR'},
 {'label': 'RXW', 'value': 'RXW'},
 {'label': 'RYR', 'value': 'RYR'}]

In [120]:
x.get_group("R0A")

,Provider_Code,Date,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
0,R0A,2022-12-31,1792,172,43.45,252,1023,657,452
105,R0A,2023-01-31,1728,171,17.74,248,1075,695,468
210,R0A,2023-02-28,1584,183,15.29,240,1013,651,439
315,R0A,2023-03-31,1549,186,14.00,251,1015,674,473

In [121]:
selected_Provider = x.get_group("R0A")
selected_Provider.head()

,Provider_Code,Date,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
0,R0A,2022-12-31,1792,172,43.45,252,1023,657,452
105,R0A,2023-01-31,1728,171,17.74,248,1075,695,468
210,R0A,2023-02-28,1584,183,15.29,240,1013,651,439
315,R0A,2023-03-31,1549,186,14.00,251,1015,674,473

In [122]:
selected_Provider.describe()

,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
count,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
mean,1663.250000,178.000000,22.620000,247.750000,1031.500000,669.250000,458.000000
std,115.618266,7.615773,13.973029,5.439056,29.320073,19.737865,15.513435
min,1549.000000,171.000000,14.000000,240.000000,1013.000000,651.000000,439.000000
25%,1575.250000,171.750000,14.967500,246.000000,1014.500000,655.500000,448.750000
50%,1656.000000,177.500000,16.515000,249.500000,1019.000000,665.500000,460.000000
75%,1744.000000,183.750000,24.167500,251.250000,1036.000000,679.250000,469.250000
max,1792.000000,186.000000,43.450000,252.000000,1075.000000,695.000000,473.000000

In [123]:
sample_std = selected_Provider.std(ddof=0)
sample_mean = selected_Provider.mean()
sample_std

C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\1324956101.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_std = selected_Provider.std(ddof=0)
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\1324956101.py:2: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  sample_mean = selected_Provider.mean()
C:\Users\Hp\AppData\Local\Temp\ipykernel_16776\1324956101.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sample_mean = selected_Provider.mean()

Date                                                              33 days 07:46:47.891070042
Daily_Average_Staff_Absence                                                       100.128355
Arriving_by_ambulance                                                               6.595453
Time_Lost_to_Ambulance_Handover_Delays_Hours                                       12.100998
Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside                      4.710361
Daily_Avg_Bed_Occupancy>7 days                                                     25.391928
Daily_Avg_Bed_Occupancy>14 days                                                    17.093493
Daily_Avg_Bed_Occupancy>21 days                                                    13.435029
dtype: object

In [28]:
(26945-27528.666667)/3006.052598

-0.19416382380944663

In [124]:
features = [
"Daily_Average_Staff_Absence",
"Arriving_by_ambulance",
"Time_Lost_to_Ambulance_Handover_Delays_Hours",
"Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside",
"Daily_Avg_Bed_Occupancy>7 days",
"Daily_Avg_Bed_Occupancy>14 days",
"Daily_Avg_Bed_Occupancy>21 days"
]

std_away = (selected_Provider[features]-sample_mean[features])/sample_std[features]
std_away = std_away + (std_away > 0)
std_away = (std_away*10)//10
std_away

,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
0,2.0,-1.0,2.0,1.0,-1.0,-1.0,-1.0
105,1.0,-2.0,-1.0,1.0,2.0,2.0,1.0
210,-1.0,1.0,-1.0,-2.0,-1.0,-2.0,-2.0
315,-2.0,2.0,-1.0,1.0,-1.0,1.0,2.0

In [125]:
std_away[std_away>=5] = 4
std_away[std_away<=-5] = -4

In [126]:
std_away

,Daily_Average_Staff_Absence,Arriving_by_ambulance,Time_Lost_to_Ambulance_Handover_Delays_Hours,Monthly_Avg_Patients_who_no_longer_meet_the_criteria_to_reside,Daily_Avg_Bed_Occupancy>7 days,Daily_Avg_Bed_Occupancy>14 days,Daily_Avg_Bed_Occupancy>21 days
0,2.0,-1.0,2.0,1.0,-1.0,-1.0,-1.0
105,1.0,-2.0,-1.0,1.0,2.0,2.0,1.0
210,-1.0,1.0,-1.0,-2.0,-1.0,-2.0,-2.0
315,-2.0,2.0,-1.0,1.0,-1.0,1.0,2.0